send_frame:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: bticino_myhome
    frame:
      required: true
      example: "*1*1*21##"
      selector:
        text:
    is_status_request:
      required: false
      default: false
      selector:
        boolean:

arm_alarm_partitions:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: bticino_myhome
    partitions:
      required: true
      selector:
        select:
          multiple: true
          options:
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
