send_frame:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: bticino_myhome
    frame:
      required: true
      example: "*1*1*21##"
      selector:
        text:
    is_status_request:
      required: false
      default: false
      selector:
        boolean:
